name: make-lint
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: lint
        run: pip install poetry
      - name: make
        run: make install
      - name: make
        run: make lint



