name: make-lint
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest

      - name: Lint
        run: make lint


